system-ghc: true
install-ghc: false

templates:
  params:
    author-name: Preetham Gujjula
    author-email: libraries@mail.preetham.io
    github-username: pgujjula

build:
  haddock-arguments:
    haddock-args:
      - "--optghc=-Wno-everything"
