system-ghc: true
install-ghc: false

# Since we use ghcup to install stack, we don't need to be notified of new stack
# versions. Actually being notified of upgrades can be a little annoying, if a
# new version is available but not yet available on ghcup.
recommend-stack-upgrade: false

templates:
  params:
    author-name: Preetham Gujjula
    author-email: libraries@mail.preetham.io
    copyright: Preetham Gujjula
    github-username: pgujjula

build:
  haddock-arguments:
    haddock-args:
      - "--optghc=-Wno-everything"

extra-lib-dirs:
- /usr/local/lib64
- /usr/local/lib
