#!/bin/bash

printf -v GIT_LOG_FORMAT_1 '%s' \
  "%C(bold blue)%h%C(reset)" \
  " - %C(bold green)(%ar)%C(reset)" \
  " %C(white)%s%C(reset)" \
  " %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)"

git log \
  --graph \
  --abbrev-commit \
  --decorate \
  "--format=format:${GIT_LOG_FORMAT_1}" \
  $@
