#!/bin/bash

printf -v GIT_LOG_FORMAT_2 '%s' \
  "%C(bold blue)%h%C(reset)" \
  " - %C(bold cyan)%aD%C(reset)" \
  " %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n" \
  "          %C(white)%s%C(reset)" \
  " %C(dim white)- %an%C(reset)"

git log \
  --graph \
  --abbrev-commit \
  --decorate \
  "--format=format:${GIT_LOG_FORMAT_2}" \
  $1
